/* Generated By:JavaCC: Do not edit this line. XMLBIFv02Constants.java */
package javabayes.Parsers.XMLBIFv02;

public interface XMLBIFv02Constants {

	int EOF = 0;
	int SOT = 3;
	int EOT = 4;
	int CT = 5;
	int OPENTAG = 6;
	int BIF = 7;
	int DEFAUL = 8;
	int ENTRY = 9;
	int FOR = 10;
	int GIVEN = 11;
	int NAME = 12;
	int NETWORK = 13;
	int PROBABILITY = 14;
	int PROPERTY = 15;
	int TABLE = 16;
	int TYPE = 17;
	int VALUE = 18;
	int VARIABLE = 19;
	int DISCRETE = 20;
	int NON_NEGATIVE_NUMBER = 21;
	int EXPONENT = 22;
	int PCDATA_CHARACTER = 23;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "<token of kind 1>", "<token of kind 2>",
			"\"<\"", "\"</\"", "\">\"", "<OPENTAG>", "\"BIF\"", "\"DEFAULT\"",
			"\"ENTRY\"", "\"FOR\"", "\"GIVEN\"", "\"NAME\"", "\"NETWORK\"",
			"\"PROBABILITY\"", "\"PROPERTY\"", "\"TABLE\"", "\"TYPE\"",
			"\"VALUE\"", "\"VARIABLE\"", "\"discrete\"",
			"<NON_NEGATIVE_NUMBER>", "<EXPONENT>", "<PCDATA_CHARACTER>", };

}
