/* Generated By:JavaCC: Do not edit this line. XMLBIFv03Constants.java */
package javabayes.ParsersXMLBIFv03;

public interface XMLBIFv03Constants {

	int EOF = 0;
	int SOT = 3;
	int EOT = 4;
	int CT = 5;
	int OPENTAG = 6;
	int EQUAL = 7;
	int BIF = 8;
	int VERSION = 9;
	int FOR = 10;
	int GIVEN = 11;
	int NAME = 12;
	int NETWORK = 13;
	int DEFINITION = 14;
	int PROPERTY = 15;
	int TABLE = 16;
	int TYPE = 17;
	int OUTCOME = 18;
	int VARIABLE = 19;
	int NATURE = 20;
	int DECISION = 21;
	int UTILITY = 22;
	int NON_NEGATIVE_NUMBER = 23;
	int EXPONENT = 24;
	int IDENTIFIER = 25;
	int LETTER = 26;
	int DIGIT = 27;
	int PCDATA_CHARACTER = 28;
	int ATTRIBUTE_STRING = 29;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "<token of kind 1>", "<token of kind 2>",
			"\"<\"", "\"</\"", "\">\"", "<OPENTAG>", "\"=\"", "\"BIF\"",
			"\"version\"", "\"FOR\"", "\"GIVEN\"", "\"NAME\"", "\"NETWORK\"",
			"\"DEFINITION\"", "\"PROPERTY\"", "\"TABLE\"", "\"TYPE\"",
			"\"OUTCOME\"", "\"VARIABLE\"", "\"\\\"nature\\\"\"",
			"\"\\\"decision\\\"\"", "\"\\\"utility\\\"\"",
			"<NON_NEGATIVE_NUMBER>", "<EXPONENT>", "<IDENTIFIER>", "<LETTER>",
			"<DIGIT>", "<PCDATA_CHARACTER>", "<ATTRIBUTE_STRING>", };

}
